**Name** : Rupali Arun KOndke
**Class** : SY-A
**Branch** : AI & DS
**Roll NO** : A-57

#           PRACTICAL NO.4

**AIM** : Numerical Computation with NumPy: Perform different computations using
 NumPy library.

**1. Explain the role of NumPy in the Python scientific computing ecosystem**.

**ANS** :

NumPy (Numerical Python) is a cornerstone library in the Python scientific computing ecosystem, providing robust support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays. Its significance stems from several key aspects:

1.  **The `ndarray` Object**: At the heart of NumPy is the `ndarray` (N-dimensional array) object. This is a powerful, efficient data structure designed to store homogenous data (all elements are of the same type). Unlike Python's built-in lists, which can hold elements of different types and are not memory-contiguous, NumPy arrays are stored in a contiguous block of memory. This characteristic is crucial for performance, especially when dealing with very large datasets.

2.  **Performance through Vectorization**: One of NumPy's most compelling features is its ability to perform operations on entire arrays without needing explicit Python loops. This concept is called **vectorization**. Most of NumPy's core routines are implemented in C or Fortran, allowing them to execute much faster than pure Python code. When you perform an operation like `array1 + array2`, NumPy handles the element-wise addition internally using optimized low-level code, leading to significant speedups for numerical computations.

3.  **Fundamental for the Scientific Python Stack**: NumPy serves as the foundational layer for almost the entire scientific Python ecosystem. Many other popular libraries either build directly upon NumPy arrays or integrate seamlessly with them:
    *   **Pandas**: The `DataFrame` object, a primary data structure in Pandas for tabular data, is built on top of NumPy arrays, leveraging its efficiency for data storage and operations.
    *   **SciPy**: This library, which offers advanced scientific and technical computing modules (like optimization, linear algebra routines, signal processing, and statistics), heavily relies on NumPy's `ndarray` as its fundamental data type.
    *   **Matplotlib and Seaborn**: These widely used plotting libraries accept NumPy arrays as input for creating various types of visualizations, making it easy to plot numerical data.
    *   **Scikit-learn**: The premier machine learning library in Python uses NumPy arrays extensively to represent datasets, features, and model parameters.
    *   **TensorFlow and PyTorch**: Even modern deep learning frameworks, while having their own tensor objects, often interact with or convert data to/from NumPy arrays.

4.  **Rich Set of Mathematical Functions**: NumPy provides an extensive collection of mathematical functions that can be applied to arrays. This includes:
    *   **Linear Algebra**: Dot products, matrix multiplication, determinants, inverses, eigenvalues, etc.
    *   **Fourier Transforms**: Functions for frequency domain analysis.
    *   **Random Number Generation**: Tools for simulating random processes and creating random data for statistical analysis.
    *   **Basic Arithmetic and Universal Functions (ufuncs)**: Element-wise operations, trigonometric functions, exponential, logarithmic, and many more, all optimized for array operations.

5.  **Memory Efficiency**: By storing data compactly and efficiently, NumPy arrays use less memory than equivalent Python lists, especially for large numerical datasets. This memory efficiency, combined with vectorized operations, makes NumPy indispensable for handling big data in scientific applications.

In summary, NumPy is the backbone of numerical computing in Python. It provides a high-performance, memory-efficient array object and a comprehensive set of mathematical tools, making it the essential enabling technology for data analysis, scientific research, machine learning, and many other data-intensive fields within the Python ecosystem.

**2.Why is NumPy considered faster than pure Python computations?**

**ANS** :  

NumPy is significantly faster than pure Python computations primarily due to:

1.  **Vectorization**: It performs operations on entire arrays at once using optimized C/Fortran code, avoiding slow Python loops.
2.  **C-level Implementation**: Its core is written in C, allowing for compiled execution speed.
3.  **Contiguous Memory**: Arrays store data of a single type in contiguous memory, enabling efficient access and reducing type-checking overhead.
4.  **Optimized Libraries**: It leverages highly tuned external libraries like BLAS/LAPACK for complex mathematical operations.
5.  **Reduced Interpreter Overhead**: By processing data in bulk outside the Python interpreter, it minimizes overhead for each individual operation.

**3. What types of mathematical operations can be performed using NumPy?**

**ANS** :

NumPy allows for a wide range of mathematical operations, including:

1.  **Basic Arithmetic**: Element-wise addition, subtraction, multiplication, division, modulo, and exponentiation.
2.  **Comparison Operations**: Element-wise comparisons (e.g., `==`, `>`, `<`) returning boolean arrays.
3.  **Aggregate Functions**: Sum, mean, median, standard deviation, variance, minimum, maximum, and product across arrays or along specific axes.
4.  **Trigonometric Functions**: Sine, cosine, tangent, and their inverse functions (element-wise).
5.  **Logarithmic and Exponential Functions**: Natural log, base-10 log, and exponential functions (element-wise).
6.  **Linear Algebra**: Dot product, matrix multiplication, determinants, inverses, eigenvalues, singular value decomposition (SVD), and solving linear systems.
7.  **Statistical Operations**: Correlation, covariance, histograms, and percentiles.
8.  **Random Number Generation**: Generating random numbers from various distributions.
9.  **Rounding and Absolute Values**: Functions for rounding, floor, ceiling, and absolute values.

**4. Explain indexing and slicing in NumPy arrays.**

**ANS** :


Indexing and slicing are fundamental for accessing parts of NumPy arrays.

### **Indexing**:
*   **Definition**: Used to select individual elements or specific parts of an array using their position.
*   **Basic Indexing**: Access elements using integer positions, e.g., `arr[row_index, col_index]`.
*   **Boolean Indexing**: Select elements based on a condition, e.g., `arr[arr > 5]`.
*   **Fancy Indexing**: Use an array of integers to select non-contiguous elements or rows/columns, e.g., `arr[[0, 2, 4]]`.

### **Slicing**:
*   **Definition**: Used to extract sub-arrays (views) from a NumPy array.
*   **Syntax**: `[start:stop:step]` applied to one or more dimensions.
    *   `start`: (inclusive) index where the slice begins.
    *   `stop`: (exclusive) index where the slice ends.
    *   `step`: (optional) the interval between elements.
*   **Examples**: `arr[1:5]` (elements from index 1 to 4), `arr[:, 2]` (all rows, 3rd column), `arr[0:2, 1:3]` (sub-array).

**Key Point**: Slicing generally returns a *view* of the original array, meaning modifications to the slice will affect the original array. Use `.copy()` to create an independent copy if needed.

**5. How does NumPy integrate with libraries like**
**a. Pandas**
**b. Matplotlib**
**c. Scikit-learn**

**ANS** :

NumPy's integration with other libraries is fundamental:

a. **Pandas**:
    *   **Foundation**: Pandas data structures (Series and DataFrame) are built directly upon NumPy's efficient `ndarray`, forming their numerical backbone.
    *   **Interoperability**: Data can be easily exchanged between Pandas objects and NumPy arrays, allowing seamless use of each library's strengths.

b. **Matplotlib**:
    *   **Data Source**: Matplotlib relies on NumPy arrays as its primary data input for plotting. Whether it's data points for a line chart or values for a heatmap, NumPy arrays are the expected format.
    *   **Data Generation**: NumPy's functions (like `linspace` for evenly spaced numbers or `random` for generating test data) are often used to create the numerical data that Matplotlib then visualizes.

c. **Scikit-learn**:
    *   **Input Standard**: Scikit-learn, the machine learning library, predominantly accepts and processes its input data (features, targets, model parameters) as NumPy arrays.
    *   **Core Performance**: The algorithms within Scikit-learn leverage NumPy's optimized operations for their underlying mathematical computations, ensuring high performance.

## Numerical Computation with NumPy: Practical Programs

Here are programs demonstrating various NumPy functionalities, categorized by difficulty.

### Weak Students (Basic)

In [ ]:
# 1. Create a NumPy array from a list.
import numpy as np

py_list = [1, 2, 3, 4, 5]
numpy_array = np.array(py_list)

print("Original Python list:", py_list)
print("NumPy array from list:", numpy_array)
print("Type of NumPy array:", type(numpy_array))

Original Python list: [1, 2, 3, 4, 5]
NumPy array from list: [1 2 3 4 5]
Type of NumPy array: <class 'numpy.ndarray'>


In [ ]:
# 2. Perform basic arithmetic operations on arrays.
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

print("Array 1:", arr1)
print("Array 2:", arr2)

# Addition
print("Addition (arr1 + arr2):", arr1 + arr2)
# Subtraction
print("Subtraction (arr1 - arr2):", arr1 - arr2)
# Multiplication
print("Multiplication (arr1 * arr2):", arr1 * arr2)
# Division
print("Division (arr1 / arr2):", arr1 / arr2)

Array 1: [10 20 30]
Array 2: [1 2 3]
Addition (arr1 + arr2): [11 22 33]
Subtraction (arr1 - arr2): [ 9 18 27]
Multiplication (arr1 * arr2): [10 40 90]
Division (arr1 / arr2): [10. 10. 10.]


In [ ]:
# 3. Find sum and mean of array elements.
import numpy as np

arr = np.array([10, 15, 20, 25, 30])

print("Array:", arr)

# Sum of elements
array_sum = np.sum(arr)
print("Sum of array elements:", array_sum)

# Mean of elements
array_mean = np.mean(arr)
print("Mean of array elements:", array_mean)

Array: [10 15 20 25 30]
Sum of array elements: 100
Mean of array elements: 20.0


In [ ]:
# 4. Reshape a one-dimensional array.
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Original 1D array:", arr_1d)
print("Shape of 1D array:", arr_1d.shape)

# Reshape to a 3x3 2D array
arr_2d = arr_1d.reshape(3, 3)
print("Reshaped 3x3 2D array:")
print(arr_2d)
print("Shape of 2D array:", arr_2d.shape)

# Reshape to a 1x9 2D array
arr_row_vector = arr_1d.reshape(1, 9)
print("Reshaped 1x9 (row vector) 2D array:")
print(arr_row_vector)

# Reshape to a 9x1 2D array
arr_col_vector = arr_1d.reshape(9, 1)
print("Reshaped 9x1 (column vector) 2D array:")
print(arr_col_vector)

Original 1D array: [1 2 3 4 5 6 7 8 9]
Shape of 1D array: (9,)
Reshaped 3x3 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of 2D array: (3, 3)
Reshaped 1x9 (row vector) 2D array:
[[1 2 3 4 5 6 7 8 9]]
Reshaped 9x1 (column vector) 2D array:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
# 5. Access specific elements using indexing.
import numpy as np

arr = np.array([[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]])

print("Original 2D array:")
print(arr)

# Access a single element (row 0, column 1)
print("Element at (0, 1):", arr[0, 1])

# Access elements from the first row
print("First row:", arr[0, :])

# Access elements from the second column
print("Second column:", arr[:, 1])

# Access a sub-array (rows 0-1, columns 1-2)
print("Sub-array (rows 0-1, cols 1-2):")
print(arr[0:2, 1:3])

# Using boolean indexing to find elements greater than 14
print("Elements greater than 14:", arr[arr > 14])

Original 2D array:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Element at (0, 1): 11
First row: [10 11 12]
Second column: [11 14 17]
Sub-array (rows 0-1, cols 1-2):
[[11 12]
 [14 15]]
Elements greater than 14: [15 16 17 18]


### Normal Students (Moderate)

In [ ]:
# 6. Perform matrix addition and multiplication.
import numpy as np

matrix_a = np.array([[1, 2],
                     [3, 4]])

matrix_b = np.array([[5, 6],
                     [7, 8]])

print("Matrix A:")
print(matrix_a)
print("Matrix B:")
print(matrix_b)

# Matrix Addition
matrix_sum = matrix_a + matrix_b
print("Matrix Addition (A + B):")
print(matrix_sum)

# Matrix Multiplication (dot product)
# For element-wise multiplication, use `*` operator
matrix_product = np.dot(matrix_a, matrix_b) # or matrix_a @ matrix_b
print("Matrix Multiplication (A @ B):")
print(matrix_product)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix Addition (A + B):
[[ 6  8]
 [10 12]]
Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]


In [ ]:
# 7. Generate random numbers using NumPy.
import numpy as np

# Generate a single random float between 0 and 1
random_float = np.random.rand()
print("Single random float:", random_float)

# Generate an array of 5 random floats between 0 and 1
random_floats_array = np.random.rand(5)
print("Array of 5 random floats:", random_floats_array)

# Generate a 2x3 array of random floats between 0 and 1
random_2x3_array = np.random.rand(2, 3)
print("2x3 array of random floats:")
print(random_2x3_array)

# Generate a single random integer between 0 (inclusive) and 10 (exclusive)
random_int = np.random.randint(10)
print("Single random integer (0-9):", random_int)

# Generate an array of 5 random integers between 1 (inclusive) and 100 (exclusive)
random_ints_array = np.random.randint(1, 100, size=5)
print("Array of 5 random integers (1-99):", random_ints_array)

# Generate a 3x2 array of random integers between 50 and 100
random_ints_2d = np.random.randint(50, 101, size=(3, 2))
print("3x2 array of random integers (50-100):")
print(random_ints_2d)

# Generate numbers from a normal distribution (mean=0, std=1)
normal_dist_numbers = np.random.randn(4)
print("Numbers from normal distribution:", normal_dist_numbers)

# Set a seed for reproducibility
np.random.seed(42)
print("Random numbers after setting seed:", np.random.rand(3))

Single random float: 0.4977558619446456
Array of 5 random floats: [0.08168011 0.93987573 0.83848931 0.73649302 0.85347938]
2x3 array of random floats:
[[0.04411082 0.69960222 0.10211183]
 [0.54317896 0.16743556 0.96367762]]
Single random integer (0-9): 5
Array of 5 random integers (1-99): [ 1  6 61 19 37]
3x2 array of random integers (50-100):
[[ 71  90]
 [ 57 100]
 [ 77  65]]
Numbers from normal distribution: [-1.11841978 -0.06729631  1.94198224  0.25120381]
Random numbers after setting seed: [0.37454012 0.95071431 0.73199394]


In [ ]:
# 8. Compute standard deviation and variance.
import numpy as np

data = np.array([10, 12, 23, 23, 16, 23, 21, 16])

print("Data array:", data)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

# For 2D array, compute along an axis
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\nMatrix:")
print(matrix)

# Standard deviation along columns (axis=0)
print("Std Dev along columns (axis=0):", np.std(matrix, axis=0))
# Standard deviation along rows (axis=1)
print("Std Dev along rows (axis=1):", np.std(matrix, axis=1))

Data array: [10 12 23 23 16 23 21 16]
Standard Deviation: 4.898979485566356
Variance: 24.0

Matrix:
[[1 2 3]
 [4 5 6]]
Std Dev along columns (axis=0): [1.5 1.5 1.5]
Std Dev along rows (axis=1): [0.81649658 0.81649658]


In [ ]:
# 9. Use NumPy functions for mathematical operations.
import numpy as np

arr = np.array([0, np.pi/2, np.pi])
print("Original array (radians):", arr)

# Trigonometric functions
print("Sine (np.sin):", np.sin(arr))
print("Cosine (np.cos):", np.cos(arr))

# Exponential and Logarithmic functions
exp_arr = np.array([1, 2, 3])
print("\nArray for exp/log:", exp_arr)
print("e^x (np.exp):", np.exp(exp_arr))
print("ln(x) (np.log):", np.log(exp_arr))

# Square root
sqrt_arr = np.array([4, 9, 16])
print("\nArray for sqrt:", sqrt_arr)
print("Square root (np.sqrt):", np.sqrt(sqrt_arr))

# Absolute value
abs_arr = np.array([-1, 0, 1])
print("\nArray for abs:", abs_arr)
print("Absolute value (np.abs):", np.abs(abs_arr))

Original array (radians): [0.         1.57079633 3.14159265]
Sine (np.sin): [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine (np.cos): [ 1.000000e+00  6.123234e-17 -1.000000e+00]

Array for exp/log: [1 2 3]
e^x (np.exp): [ 2.71828183  7.3890561  20.08553692]
ln(x) (np.log): [0.         0.69314718 1.09861229]

Array for sqrt: [ 4  9 16]
Square root (np.sqrt): [2. 3. 4.]

Array for abs: [-1  0  1]
Absolute value (np.abs): [1 0 1]


In [ ]:
# 10. Compare Python lists and NumPy arrays (speed and memory).
import numpy as np
import time
import sys

# --- Speed Comparison ---
list_size = 1000000

# Python List
py_list1 = list(range(list_size))
py_list2 = list(range(list_size))

start_time = time.time()
result_list = [x + y for x, y in zip(py_list1, py_list2)]
end_time = time.time()
print(f"Time taken for list addition: {end_time - start_time:.6f} seconds")

# NumPy Array
numpy_arr1 = np.arange(list_size)
numpy_arr2 = np.arange(list_size)

start_time = time.time()
result_numpy = numpy_arr1 + numpy_arr2
end_time = time.time()
print(f"Time taken for NumPy array addition: {end_time - start_time:.6f} seconds")

# --- Memory Comparison ---
# Python List (size of one element * number of elements + overhead)
list_mem = sys.getsizeof(0) * list_size + sys.getsizeof(py_list1) # Approximation
print(f"\nMemory taken by Python list (approx): {list_mem / (1024*1024):.2f} MB")

# NumPy Array (size of data type * number of elements)
numpy_mem = numpy_arr1.itemsize * numpy_arr1.size
print(f"Memory taken by NumPy array: {numpy_mem / (1024*1024):.2f} MB")

print("\nConclusion: NumPy arrays are generally much faster and more memory-efficient for numerical operations compared to Python lists.")

Time taken for list addition: 0.082050 seconds
Time taken for NumPy array addition: 0.005249 seconds

Memory taken by Python list (approx): 34.33 MB
Memory taken by NumPy array: 7.63 MB

Conclusion: NumPy arrays are generally much faster and more memory-efficient for numerical operations compared to Python lists.


### Bright Students (Advanced)

In [ ]:
# 11. Implement vectorized operations for performance comparison.
import numpy as np
import time

array_size = 1000000

a = np.random.rand(array_size)
b = np.random.rand(array_size)

# --- Vectorized NumPy operation ---
start_time = time.time()
result_np = a * b + np.sin(a)
end_time = time.time()
print(f"NumPy Vectorized Time: {end_time - start_time:.6f} seconds")

# --- Equivalent Python loop (for comparison) ---
# Note: This will be significantly slower for large arrays
result_py = []
start_time = time.time()
for i in range(array_size):
    result_py.append(a[i] * b[i] + np.sin(a[i])) # using np.sin for consistency
end_time = time.time()
print(f"Python Loop Time:        {end_time - start_time:.6f} seconds")

print(f"\nNumPy is approximately {round((end_time - start_time) / (np.array(result_np).min() - np.array(result_np).max()), 0) if (np.array(result_np).min() - np.array(result_np).max()) != 0 else 0}x faster (depending on operations and hardware) for this operation.")

NumPy Vectorized Time: 0.025879 seconds
Python Loop Time:        2.005196 seconds

NumPy is approximately -1.0x faster (depending on operations and hardware) for this operation.


In [ ]:
# 12. Solve a system of linear equations.
import numpy as np

# Consider the system:
# 2x + 3y = 8
# x  + 2y = 5

# Represent coefficients as a matrix A
A = np.array([[2, 3],
              [1, 2]])

# Represent constants as a vector B
B = np.array([8, 5])

print("Coefficient Matrix A:")
print(A)
print("Constant Vector B:", B)

# Solve for X (where X is [x, y]) using np.linalg.solve
X = np.linalg.solve(A, B)

print("\nSolution (x, y):", X)
print(f"x = {X[0]:.2f}, y = {X[1]:.2f}")

# Verification: A @ X should be equal to B
print("Verification (A @ X):", np.dot(A, X))

Coefficient Matrix A:
[[2 3]
 [1 2]]
Constant Vector B: [8 5]

Solution (x, y): [1. 2.]
x = 1.00, y = 2.00
Verification (A @ X): [8. 5.]


In [ ]:
# 13. Perform broadcasting operations.
import numpy as np

# Example 1: Scalar-array addition
arr = np.array([1, 2, 3])
scalar = 10
result_scalar = arr + scalar
print("Array + Scalar:", result_scalar)

# Example 2: Array of different shapes
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]]) # Shape (2, 3)
arr_1d = np.array([10, 20, 30]) # Shape (3,)

# NumPy stretches arr_1d to match the rows of arr_2d
result_broadcast = arr_2d + arr_1d
print("\n2D Array + 1D Array (broadcasted):")
print(result_broadcast)

# Example 3: Broadcasting with incompatible shapes (will raise an error)
# arr_2d_incompatible = np.array([[10, 20],
#                                 [30, 40]]) # Shape (2, 2)
# try:
#     arr_2d + arr_2d_incompatible
# except ValueError as e:
#     print(f"\nError for incompatible shapes: {e}")

# Example 4: Adding a column vector to a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]]) # Shape (2, 3)
column_vector = np.array([[10],
                          [20]]) # Shape (2, 1)

# NumPy stretches the column_vector across columns of the matrix
result_col_broadcast = matrix + column_vector
print("\nMatrix + Column Vector (broadcasted):")
print(result_col_broadcast)

Array + Scalar: [11 12 13]

2D Array + 1D Array (broadcasted):
[[11 22 33]
 [14 25 36]]

Matrix + Column Vector (broadcasted):
[[11 12 13]
 [24 25 26]]


In [ ]:
# 14. Analyze large datasets using NumPy arrays.
import numpy as np
import time

# Simulate a large dataset (e.g., sensor readings, financial data)
dataset_size = 5000000 # 5 million data points
large_data = np.random.rand(dataset_size) * 100 # Random numbers between 0 and 100

print(f"Created a large dataset of {dataset_size} elements.")

# --- Basic analysis (mean, median, std dev, min, max) ---
start_time = time.time()
mean_val = np.mean(large_data)
median_val = np.median(large_data)
std_val = np.std(large_data)
min_val = np.min(large_data)
max_val = np.max(large_data)
end_time = time.time()

print(f"\nTime for basic analysis: {end_time - start_time:.6f} seconds")
print(f"Mean: {mean_val:.2f}")
print(f"Median: {median_val:.2f}")
print(f"Standard Deviation: {std_val:.2f}")
print(f"Min: {min_val:.2f}")
print(f"Max: {max_val:.2f}")

# --- Filtering data ---
start_time = time.time()
threshold = 75
high_values = large_data[large_data > threshold]
end_time = time.time()

print(f"\nTime for filtering: {end_time - start_time:.6f} seconds")
print(f"Number of values > {threshold}: {len(high_values)}")
print(f"First 5 high values: {high_values[:5]}")

# --- Data transformation (e.g., normalization) ---
start_time = time.time()
normalized_data = (large_data - mean_val) / std_val
end_time = time.time()

print(f"\nTime for normalization: {end_time - start_time:.6f} seconds")
print(f"First 5 normalized values: {normalized_data[:5]}")

Created a large dataset of 5000000 elements.

Time for basic analysis: 0.125643 seconds
Mean: 50.00
Median: 50.00
Standard Deviation: 28.87
Min: 0.00
Max: 100.00

Time for filtering: 0.037817 seconds
Number of values > 75: 1249876
First 5 high values: [99.07974192 82.01925149 90.4737209  92.19089311 84.56395927]

Time for normalization: 0.018956 seconds
First 5 normalized values: [-0.22275196 -0.96773817  1.69995681  0.53421709  1.10905807]


In [ ]:
# 15. Optimize numerical computations using NumPy functions.
import numpy as np
import time

# Problem: Calculate the sum of squares of elements in a large array.
array_size = 5000000
large_array = np.random.rand(array_size)

print(f"Array size: {array_size}")

# --- Method 1: Using Python loop (less optimized) ---
start_time = time.time()
sum_of_squares_py = 0
for x in large_array:
    sum_of_squares_py += x*x
end_time = time.time()
print(f"\nPython loop sum of squares: {sum_of_squares_py:.4f} (Time: {end_time - start_time:.6f} s)")

# --- Method 2: Using NumPy vectorized operation (optimized) ---
start_time = time.time()
sum_of_squares_np = np.sum(large_array**2)
end_time = time.time()
print(f"NumPy vectorized sum of squares: {sum_of_squares_np:.4f} (Time: {end_time - start_time:.6f} s)")

# --- Method 3: Using np.dot (for sum of squares, slightly different approach but demonstrates optimization) ---
# For sum of squares, this is (a.T @ a) or np.dot(a, a) if a is 1D
start_time = time.time()
sum_of_squares_dot = np.dot(large_array, large_array)
end_time = time.time()
print(f"NumPy np.dot sum of squares: {sum_of_squares_dot:.4f} (Time: {end_time - start_time:.6f} s)")

print("\nObservation: NumPy's vectorized operations are significantly faster than explicit Python loops for large numerical computations.")

Array size: 5000000

Python loop sum of squares: 1666888.9304 (Time: 1.360745 s)
NumPy vectorized sum of squares: 1666888.9304 (Time: 0.022125 s)
NumPy np.dot sum of squares: 1666888.9304 (Time: 0.003268 s)

Observation: NumPy's vectorized operations are significantly faster than explicit Python loops for large numerical computations.


**CONCLUSION** :

NumPy is fundamental for numerical computing in Python. It provides high-performance array objects and optimized mathematical functions, leading to significant speed and memory efficiency over pure Python, and serves as the backbone for libraries like Pandas, Matplotlib, and Scikit-learn.

